name: VPS-NAM-AUTO-INFO
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Toi uu mang (BBR)
        run: |
          sudo sysctl -w net.core.default_qdisc=fq
          sudo sysctl -w net.ipv4.tcp_congestion_control=bbr

      - name: 2. Ket noi Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --accept-dns=false

      - name: 3. Thiet lap SSH & User
        run: |
          sudo apt update && sudo apt install -y openssh-server jq
          # Dat mat khau la: vps9999
          echo "runner:vps9999" | sudo chpasswd
          sudo service ssh start

      - name: 4. HIEN THI THONG TIN DANG NHAP
        run: |
          IP_TAILSCALE=$(tailscale ip -4)
          echo "=========================================="
          echo "    THONG TIN VPS LINUX CUA BAN         "
          echo "=========================================="
          echo "📍 IP: $IP_TAILSCALE"
          echo "👤 USER: runner"
          echo "🔑 PASS: vps9999"
          echo "🚪 PORT: 22"
          echo "=========================================="
          echo "Dung IP nay de nhap vao Termius nhe!"

      - name: 5. Treo may 6 tieng
        run: sleep 21600
